<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_movel_arm">

<!-- INERTIAS -->
    <xacro:macro name="box_inertia" params="mass xS yS zS">
		<inertia 	ixx="${1/12*mass*(zS*zS + yS*yS)}"
					iyy="${1/12*mass*(zS*zS + xS*xS)}" 
					izz="${1/12*mass*(xS*xS + yS*yS)}" 
					ixy="0.0" ixz="0.0" iyz="0.0" />
	</xacro:macro>
	<xacro:macro name="cylinder_inertia" params="mass r h">
		<inertia 	ixx="${mass * (3 * r * r + h * h) / 12}" ixy="0" ixz="0"
					iyy="${mass * r * r / 2}" iyz="0"
					izz="${mass * (3 * r * r + h * h) / 12}" />
	</xacro:macro>
	
	<!-- Robot dimensions and Propertys -->
	<xacro:property name="tube_length" value="0.2" />
	<xacro:property name="tube_radius" value="0.01" />
	<xacro:property name="tube_mass" value="0.1" />
	<xacro:property name="servo_mass" value="0.3" />
	
	<xacro:macro name="servo" params="prefix mass xS yS zS origins_xyz origins_rpy">
		<link name="Box${prefix}_link">
			<visual>
				<geometry>
					<box size="${xS} ${yS} ${zS}"/>
				</geometry>
				<origin xyz="${origins_xyz}" rpy="${origins_rpy}" />
			</visual>
			<collision>
				<origin xyz="${origins_xyz}" rpy="${origins_rpy}"/>
				<geometry>
					<box size="${xS} ${yS} ${zS}"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz="${origins_xyz}" rpy="${origins_rpy}" />
				<mass value="${mass}" />
				<xacro:box_inertia mass="${mass}" xS="${xS}" yS="${yS}" zS="${zS}"/>
			</inertial>
		</link>
	</xacro:macro>
	
	<xacro:macro name="tube" params="prefix length radius mass" >
		<link name="Tube${prefix}_link">
			<visual>
				<geometry>
					<cylinder length="${length}" radius="${radius}"/>
				</geometry>
				<origin rpy="1.57075 0 0" xyz="0 ${length / 2} 0"/>
			</visual>
			<collision>
				<origin rpy="1.57075 0 0" xyz="0 ${length / 2} 0"/>
				<geometry>
					<cylinder length="${length}" radius="${radius}"/>
				</geometry>
			</collision>
			<inertial>
				<origin rpy="1.57075 0 0" xyz="0 ${length / 2} 0"/>
				<mass value="${mass}" />
				<xacro:cylinder_inertia mass="${mass}" r="${radius}" h="${length}" />
			</inertial>
		</link>
	</xacro:macro>
	
	<xacro:servo prefix="0" mass="${servo_mass}" xS="0.06" yS="0.04" zS="0.03" origins_xyz="-0.01 0.055 0" 	origins_rpy="0 0 0"/>
	<xacro:servo prefix="1" mass="${servo_mass}" xS="0.03" yS="0.05" zS="0.02" origins_xyz="0 0.025 0" 		origins_rpy="0 0 0"/>
	<xacro:servo prefix="2" mass="${servo_mass}" xS="0.05" yS="0.03" zS="0.02" origins_xyz="-0.015 0.04 0" 	origins_rpy="0 0 0"/>
	<xacro:servo prefix="3" mass="${servo_mass}" xS="0.03" yS="0.05" zS="0.02" origins_xyz="0 0.026 0" 		origins_rpy="0 0 0"/>

	<xacro:tube prefix="0" radius="${tube_radius}" length="${tube_length}" mass="${tube_mass}" />
	<xacro:tube prefix="1" radius="${tube_radius}" length="${tube_length}" mass="${tube_mass}" />
	
	<link name="ombro_link">
		<visual>
			<geometry>
				<cylinder length="0.1" radius="0.025"/>
			</geometry>
			<origin rpy="0 1.57075 0"/>
		</visual>
		<collision>
			<origin rpy="0 1.57075 0"/>
			<geometry>
				<cylinder length="0.1" radius="0.025"/>
			</geometry>
		</collision>
		<inertial>
			<origin rpy="0 1.57075 0" />
			<mass value="0.5" />
			<xacro:cylinder_inertia mass="0.5" r="0.025" h="0.1" />
		</inertial>
	</link>
	
	<link name="gripper_link">
		<visual>
			<geometry>
				<box size="0.1 0.1 0.03"/>
			</geometry>
			<origin xyz="0 0.07 0"/>
		</visual>
		<collision>
			<origin xyz="0 0.07 0"/>
			<geometry>
				<box size="0.1 0.1 0.03"/>
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0.07 0"/>
			<mass value="0.3" />
			<xacro:box_inertia mass="0.3" xS="0.1" yS="0.1" zS="0.03"/>
		</inertial>
	</link>
	
	<!-- Revolute Joints -->
	<joint name="joint1" type="revolute">
		<parent link="ombro_link"/>
		<child link="Box0_link"/>
		<origin xyz="0 0 0"/>
		<limit lower="-1.57075" upper="1.57075" effort="1000" velocity="10"/>
		<axis xyz="1 0 0"/>
	</joint>	
	
	<joint name="joint2" type="revolute">
		<parent link="Box0_link"/>
		<child link="Tube0_link"/>
		<origin xyz="0 0.075 0"/>
		<limit lower="-1.57075" upper="1.57075" effort="1000" velocity="10"/>
		<axis xyz="0 1 0"/>
	</joint>	
	
	<joint name="joint4" type="revolute">
		<parent link="Box1_link"/>
		<child link="Box2_link"/>
		<origin xyz="0 0.04 0"/>
		<limit lower="-3.14" upper="3.14" effort="1000" velocity="10"/>
		<axis xyz="1 0 0"/>
	</joint>
	
	<joint name="joint5" type="revolute">
		<parent link="Box2_link"/>
		<child link="Tube1_link"/>
		<origin xyz="0 0.055 0"/>
		<limit lower="-3.14" upper="3.14" effort="1000" velocity="10"/>
		<axis xyz="0 1 0"/>
	</joint>
	
	<joint name="joint7" type="revolute">
		<parent link="Box3_link"/>
		<child link="gripper_link"/>
		<origin xyz="0 0.04 0"/>
		<limit lower="-1.57075" upper="1.57075" effort="1000" velocity="10"/>
		<axis xyz="1 0 0"/>
	</joint>
	
	<!-- Fixed joints -->
	<joint name="joint3" type="fixed">
		<parent link="Tube1_link"/>
		<child link="Box3_link"/>
		<origin xyz="0 0.2 0"/>
	</joint>
	
	<joint name="joint6" type="fixed">
		<parent link="Tube0_link"/>
		<child link="Box1_link"/>
		<origin xyz="0 0.2 0"/>
	</joint>
	
	<!-- Controllers -->
	<xacro:macro name="controllers" params="prefix">
		<transmission name="${prefix}_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
			<actuator name="${prefix}_motor">
				<mechanicalReduction>1</mechanicalReduction>
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</actuator>
		</transmission>
	</xacro:macro>
	<xacro:controllers prefix="joint1" />
	<xacro:controllers prefix="joint2" />
	<xacro:controllers prefix="joint4" />
	<xacro:controllers prefix="joint5" />
	<xacro:controllers prefix="joint7" />
	
	<!-- Gazebo plugin -->
	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/robotic_arm</robotNamespace> <!-- namespace for controllers etc... -->
		</plugin>
	</gazebo>
	
	<!-- GAZEBO COLORS -->
	<gazebo reference="wall_link">  
		<visual>  
			<material>
				<ambient>0.4 0.7 0.4 0.6</ambient>  
				<diffuse>0.4 0.7 0.4 0.6</diffuse>  
				<specular>0.4 0.7 0.4 0.6</specular>  
				<emissive>0.0 0.0 0.0 0.0</emissive>  
			</material>  
		</visual>  
	</gazebo>
	<gazebo reference="ombro_link">  
		<visual>  
			<material>
				<ambient>0.6 0.6 0.6 1.0</ambient>  
				<diffuse>0.6 0.6 0.6 1.0</diffuse>  
				<specular>0.6 0.6 0.6 1.0</specular>  
				<emissive>0.0 0.0 0.0 0.0</emissive> 
			</material>
		</visual>  
	</gazebo>
	<gazebo reference="gripper_link">  
		<visual>  
			<material>
				<ambient>0.4 0.4 0.7 1.0</ambient>  
				<diffuse>0.4 0.4 0.7 1.0</diffuse>  
				<specular>0.4 0.4 0.7 1.0</specular>  
				<emissive>0.0 0.0 0.0 0.0</emissive> 
			</material>
		</visual>  
	</gazebo>
	<xacro:macro name="servo_color" params="link_name">
		<gazebo reference="${link_name}">  
			<visual>  
				<material>
					<ambient>0 0 0 1.0</ambient>  
					<diffuse>0 0 0 1.0</diffuse>  
					<specular>0 0 0 1.0</specular>  
					<emissive>0.0 0.0 0.0 0.0</emissive> 
				</material>
			</visual>  
		</gazebo>
	</xacro:macro>
	<xacro:servo_color link_name="Box0_link" />
	<xacro:servo_color link_name="Box1_link" />
	<xacro:servo_color link_name="Box2_link" />
	<xacro:servo_color link_name="Box3_link" />
	<xacro:macro name="tube_color" params="link_name">
		<gazebo reference="${link_name}">  
			<visual>  
				<material>
					<ambient>0.7 0.3 0.3 1.0</ambient>  
					<diffuse>0.7 0.3 0.3 1.0</diffuse>  
					<specular>0.7 0.3 0.3 1.0</specular>  
					<emissive>0.0 0.0 0.0 0.0</emissive> 
				</material>
			</visual>  
		</gazebo>
	</xacro:macro>
	<xacro:tube_color link_name="Tube0_link" />
	<xacro:tube_color link_name="Tube1_link" />
	
	<!-- Didn't work
	<xacro:macro name="gazebo_propertys" params="link_name">
		<gazebo reference="${link_name}">
			<turnGravityOff>true</turnGravityOff>
		</gazebo>
    </xacro:macro>
    <xacro:gazebo_propertys link_name="Box0_link" />
    <xacro:gazebo_propertys link_name="Box1_link" />
    <xacro:gazebo_propertys link_name="Box2_link" />
    <xacro:gazebo_propertys link_name="Box3_link" />
    <xacro:gazebo_propertys link_name="Box4_link" />
    <xacro:gazebo_propertys link_name="Tube0_link" />
    <xacro:gazebo_propertys link_name="Tube1_link" />
    <xacro:gazebo_propertys link_name="wall_link" />
    <xacro:gazebo_propertys link_name="ombro_link" />
    <xacro:gazebo_propertys link_name="gripper_link" />
    -->
	
</robot>
